apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-dev
spec:
  replicas: 4
  selector:
    app: nginx-dev
  template:
    metadata:
      name: nginx-dev
      labels:
        app: nginx-dev
    spec:
      containers:
      - name: nginx-dev
        image: nginx
        ports:
        - containerPort: 90
