apiVersion: v1
kind: Service
metadata:
  namespace: kube-demo
  name: nginx-kube
spec:
  ports:
  - nodePort: 31500
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
